# Generated by Django 5.0.6 on 2024-05-10 18:21

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategoryDb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('status', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogDb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
                ('meta_keyword', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='article_images')),
                ('status', models.BooleanField(default=True)),
                ('published_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('likes', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('views', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('comments', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='myApp.blogcategorydb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
